# -*- coding: utf-8 -*-
"""Python Digital AI Hub.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16eOuTRvkGg0zorUoYV6ljU4C2SiqCB7_
"""

## 3 ŞUBAT ÖDEVİ

sayi = int(input("Bir sayı giriniz. "))
kat = int(input("Kaçar kaçar gidelim? "))
print(sayi)

while sayi*kat < 20000:
  sayi *= kat
  print(sayi)

# 3 ŞUBAT ÖDEVİ

print("UMUR BANKASI'NA HOŞ GELDİNİZ\n")
kullanıcıadı = input("Kullanıcı Adınız: ")
şifre = input("Şifreniz: ")
anne = input("Annenizin Kızlık Soyadı: ")

if kullanıcıadı == "umurketen" and şifre == "1234" and anne[-2:].upper() == "AÇsa":
  print("\nBaşarıyla giriş yapıldı.\nKullanıcı Adı: umurketen\nŞifre: 1234\nAnne Adı Kızlık Soyadının Son 2 Harfi: AÇ")
else:
  print("\nHatalı giriş yapıldı. Bilgileriniz şöyleydi:\nKullanıcı Adı: umurketen\nŞifre: 1234\nAnne Adı Kızlık Soyadının Son 2 Harfi: AÇ")

# 4 ŞUBAT ÖDEVİ

rehber = {}

isim = input("İsim: ")
soyisim = input("Soyisim: ")
telefon = int(input("Telefon: "))
rehber["İsim"] = isim
rehber["Soyisim"] = soyisim
rehber["Telefon"] = telefon

print(rehber)

# 4 ŞUBAT ÖDEVİ

midterm = int(input("Midterm Notu: "))
final = int(input("Final Notu: "))
sunum = int(input("Sunum Notu: "))
ortalama = (midterm*0.3 + final*0.5 + sunum*0.2) 

print("\nMidterm ağırlığı %30, final sınavı ağırlığı %50, sunum ağırlığı %20'dir.\n")
dicti = {"Midterm Notu":midterm,"Final Notu":final,"Sunum notu":sunum,"Ortalama":ortalama}
print(dicti)

if ortalama > 90:
  print("\nBaşarıyla geçtiniz!")
elif ortalama > 60:
  print("Sınıfı geçtiniz.")
elif ortalama > 40:
  print("Bir şekilde geçtiniz...")
else:
  print("Seneye görüşürüz :(")

# 4 ŞUBAT ÖDEVİ

liste = [i for i in range(8)]
print(liste)

liste = [2*i for i in range(8) if i%3 == 0]
print(liste)

liste = [i for i in range(8)]
print(liste)